### ISSUE TITLE
Compatibility Issue with Django 4.0

### ISSUE THREAD

**Issue by mmhy2003** [silviolleite/django-pwa#83]
Hello,

I upgraded an old project of mine from Django 3 to 4.
And I found a compatibility issue while integrating your module with the project.

BR,

**Comment by elhachimi-ch** [comment]
Assalam,
I have the same error, I think the "url" should be changed to "re_path" in import url as "url" is deprecated in Django 4.
Thank you.

**Comment by eeriksp** [comment]
This issue is fixed once #88 has been accepted.

**Comment by abhinav-j07** [comment]
Downloaded the latest version. Still getting an error with this.

/lib/python3.8/site-packages/pwa/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/Users/abhinav/Library/Caches/pypoetry/virtualenvs/10pc-main4-st3C-Inu-py3.8/lib/python3.8/site-packages/django/conf/urls/__init__.py)

**Comment by Fazendaaa** [comment]
The fixed version is not published yet, you can surely circumvent this by installing the package directly from GitHub as it's in the master branch:

```shell
poetry add git+https://github.com/silviolleite/django-pwa
```

In case you already aren't using [poetry](https://python-poetry.org/) yet:

```shell
pip install git+https://github.com/silviolleite/django-pwa
```

**Comment by abhinav-j07** [comment]
Thanks Lucas. Much appreciated.

**Comment by DekuMawuli** [comment]
I had the same issue as at today. In case you also encounter same, navigate to the pwa/urls.py
change, **"from django.conf.urls import urls"** to `from django.urls import re_path`

**Comment by hartungstenio** [comment]
Hello. I just released `1.1.0` with the contents of `master` branch and the fix introduced by #68 .
